### ISSUE TITLE
List on probot.github.io

### ISSUE THREAD

**Issue by bkeepers** [dessant/support-requests#1]
Hey @dessant, this app looks great! Would you be interested in having this listed on probot.github.io? Here are the [directions for submitting it to the site](https://github.com/probot/probot.github.io/blob/master/CONTRIBUTING.md#adding-your-app) if you're interested.

**Comment by dessant** [comment]
Thanks a lot! Sure, I'll make a PR tomorrow.

**Comment by dessant** [comment]
Submitted in https://github.com/probot/probot.github.io/pull/99.
