### ISSUE TITLE
Close `support` issues as Not Planned

### ISSUE THREAD

**Issue by Julian-O** [dessant/support-requests#10]
GitHub supports (manually) closing an issue as either Complete or Not Planned. I assume, without checking, that it permits the same programmatically.

This GitHub action closes the items as Complete. I think Not Planned is a better fit.

I can't see how this makes any practical difference in the real world, apart from signalling a message to users, so please treat this as low priority.

**Comment by dessant** [comment]
Thanks for the feature request! You could also use Label Actions until this is implemented, it already supports `close-reason`.

https://github.com/dessant/label-actions
